<Solution xmlns:i="http://www.w3.org/2001/XMLSchema-instance" z:Id="i1" xmlns:z="http://schemas.microsoft.com/2003/10/Serialization/" xmlns="http://schemas.datacontract.org/2004/07/NationalInstruments.PackageBuilder.Engine">
    <Name>Power Test</Name>
    <SourceItems>
        <SourceItem z:Id="i2">
            <PluginConfigurationOptions />
            <RelativePath>Power Test.aliases</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i3">
            <PluginConfigurationOptions />
            <RelativePath>Power Test.lvlps</RelativePath>
            <DependentItems />
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i4">
            <PluginConfigurationOptions />
            <RelativePath>Power Test.lvproj</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i2" />
                <SourceItem z:Ref="i3" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
        <SourceItem z:Id="i5">
            <PluginConfigurationOptions />
            <RelativePath>Power Test.seq</RelativePath>
            <DependentItems>
                <SourceItem z:Ref="i4" />
            </DependentItems>
            <IsDiscoverable>true</IsDiscoverable>
        </SourceItem>
    </SourceItems>
    <InputSourceItems>
        <SourceItem z:Ref="i5" />
    </InputSourceItems>
    <Distributions>
        <Distribution z:Id="i6" i:type="Package">
            <DistributionItems>
                <DistributionItem z:Id="i7" i:type="DistributionFileItem">
                    <DestinationRelativePath>[TestStand Public Documents]\Power Test.seq</DestinationRelativePath>
                    <Name>Power Test.seq</Name>
                    <SourceItem z:Ref="i5" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i8" i:type="DistributionFileItem">
                    <DestinationRelativePath>[TestStand Public Documents]\Power Test.lvproj</DestinationRelativePath>
                    <Name>Power Test.lvproj</Name>
                    <SourceItem z:Ref="i4" />
                    <PluginConfigurationOptions>
                        <ConfigurationOption z:Id="i9">
                            <Definition z:Id="i10">
                                <Description i:nil="true" />
                                <Name>Include all files in LabVIEW project</Name>
                            </Definition>
                            <HasDefaultValues>true</HasDefaultValues>
                            <Value z:Id="i11" i:type="BooleanConfigurationOptionValue" />
                        </ConfigurationOption>
                    </PluginConfigurationOptions>
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i12" i:type="DistributionFileItem">
                    <DestinationRelativePath>[TestStand Public Documents]\Power Test.aliases</DestinationRelativePath>
                    <Name>Power Test.aliases</Name>
                    <SourceItem z:Ref="i2" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
                <DistributionItem z:Id="i13" i:type="DistributionFileItem">
                    <DestinationRelativePath>[TestStand Public Documents]\Power Test.lvlps</DestinationRelativePath>
                    <Name>Power Test.lvlps</Name>
                    <SourceItem z:Ref="i3" />
                    <PluginConfigurationOptions />
                    <ProcessDuringStaging>true</ProcessDuringStaging>
                </DistributionItem>
            </DistributionItems>
            <Name>Power Test</Name>
            <OutputDirectory>Packages</OutputDirectory>
            <PluginConfigurationOptions />
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <Architecture>windows_x64</Architecture>
            <AutoIncrementVersion>Build</AutoIncrementVersion>
            <BuildStatus z:Id="i14">
                <BuildEverSuccessful>true</BuildEverSuccessful>
                <FileName>ni-power-test_19.0.0.1_windows_x64.nipkg</FileName>
                <Version>19.0.0.1</Version>
            </BuildStatus>
            <CompanyName>MyCompany</CompanyName>
            <CustomExecutes />
            <DisplayName>Power Test</DisplayName>
            <DisplayVersion>19.0.0</DisplayVersion>
            <FileName>ni-power-test_19.0.0.2_windows_x64.nipkg</FileName>
            <MaintainerEmail>email@mycompany.com</MaintainerEmail>
            <MaintainerName>NI</MaintainerName>
            <Messages xmlns:d4p1="http://schemas.microsoft.com/2003/10/Serialization/Arrays" />
            <PackageName>ni-power-test</PackageName>
            <PackageRelationships>
                <PackageRelationship z:Id="i15">
                    <Constraint>LaterOrEqual</Constraint>
                    <DisplayName>LabVIEW Runtime (64-bit)</DisplayName>
                    <PackageName>ni-labview-2019-runtime-engine</PackageName>
                    <Relation>Depends</Relation>
                    <Version>19.0.0.49152-0+f0</Version>
                    <VersionType>AutoUpdate</VersionType>
                </PackageRelationship>
                <PackageRelationship z:Id="i16">
                    <Constraint>LaterOrEqual</Constraint>
                    <DisplayName>TestStand Runtime (64-bit)</DisplayName>
                    <PackageName>ni-teststand-2019-runtime</PackageName>
                    <Relation>Depends</Relation>
                    <Version>19.0.0.49154-0+f2</Version>
                    <VersionType>AutoUpdate</VersionType>
                </PackageRelationship>
            </PackageRelationships>
            <ProductName>MyProduct</ProductName>
            <Section>Application Software</Section>
            <Synopsis>TestStand example that publishes TDMS files</Synopsis>
            <Version>19.0.0.2</Version>
        </Distribution>
    </Distributions>
    <Feeds>
        <Feed z:Id="i17" i:type="LocalFeed">
            <Configurable>false</Configurable>
            <Enabled>false</Enabled>
            <Name>Power Test</Name>
            <Products>
                <Product z:Id="i18" i:type="LocalFeedProduct">
                    <Package z:Ref="i6" />
                </Product>
            </Products>
            <Uri>LocalRepositories</Uri>
        </Feed>
    </Feeds>
    <DistributionGroups>
        <DistributionGroup z:Id="i19">
            <Distributions>
                <Distribution z:Ref="i6" />
            </Distributions>
            <Name>Distribution Group</Name>
            <PrebuildAnalysisEnabled>true</PrebuildAnalysisEnabled>
            <StageDirectory>ProcessingStage</StageDirectory>
        </DistributionGroup>
    </DistributionGroups>
    <TestStandMode>true</TestStandMode>
    <PluginConfigurationOptions>
        <ConfigurationOption z:Id="i20">
            <Definition z:Id="i21">
                <Description i:nil="true" />
                <Name>TestStand Options</Name>
            </Definition>
            <HasDefaultValues>true</HasDefaultValues>
            <Value z:Id="i22" i:type="DialogConfigurationOptionValue">
                <Values>
                    <ConfigurationOptionValue z:Id="i23" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i24" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i25" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i26" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i27" i:type="StringConfigurationOptionValue">
                        <Value>SupportVIs</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i28" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i29" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i30" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i31" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i32" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i33" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i34" i:type="BooleanConfigurationOptionValue">
                        <Value>true</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i35" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i36" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i37" i:type="PathConfigurationOptionValue">
                        <RelativePath />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i38" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i39" i:type="BooleanConfigurationOptionValue" />
                    <ConfigurationOptionValue z:Id="i40" i:type="StringConfigurationOptionValue">
                        <Value>[BootVolume]</Value>
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i41" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i42" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                    <ConfigurationOptionValue z:Id="i43" i:type="StringConfigurationOptionValue">
                        <Value />
                    </ConfigurationOptionValue>
                </Values>
            </Value>
        </ConfigurationOption>
    </PluginConfigurationOptions>
</Solution>